---
jb_toolbox_version: '1.11.4269'
hostname: workstation01
tor_browser_version: '8.0'
burpsuite_version: '1.7.36'
burpsuite_version_underscore: "{{burpsuite_version | regex_replace('\\.', '_')}}"
package_manager_installed_packages:
  - vim
  - tmux
  - java-1.8.0-openjdk-devel
  - dotnet-sdk-2.1
  - ansible
  - gnome-tweak-tool
  - chrome-gnome-shell
  - powerline
  - tmux-powerline
  - dnf-plugins-core
  - docker-ce
  - unzip
  - vagrant
  - vagrant-libvirt
  - vagrant-libvirt-doc
  - '@virtualization'
  - terminator
  - xclip
  - npm
  - redhat-rpm-config
  - nfs-utils
pip_packages:
  - awscli
  - aws-sam-cli
firewall_services:
  - rpc-bind
  - mountd
  - nfs
ansible_packages:
- libselinux-python
- redhat-rpm-config
- python-devel
- python3-devel
mozilla_packages:
- '@development-tools'
- '@c-development'
- autoconf213
- gtk2-devel
- gtk3-devel
- libXt-devel
- GConf2-devel
- dbus-glib-devel
- yasm-devel
- alsa-lib-devel
- pulseaudio-libs-devel
- hg
- llvm
- clang
- llvm-devel
- cargo
ruby_installed_gems:
  - gist
systemd_services:
  - docker
  - libvirtd
  - nfs-server
users_groups:
  - docker
  - libvirt
...
